# Generated by Django 3.1.2 on 2020-10-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureUrl', models.CharField(max_length=250)),
                ('returnData', models.TextField()),
                ('queryDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
